### ISSUE TITLE
This does not work with RTR

### ISSUE THREAD

**Issue by ethindp** [RastislavKish/nvda2speechd#6] opened 2022-10-30 21:41 UTC
I don't know if this doesn't work with other things but neither the official binaries nor the binaries that I compiled from source work at all. I start nvda2speechd, but when I launch a game like road to rage, it doesn't report a connection nor does it actually work at all. I have tried setting the host and port env var and still nothing. I have replaced the NVDA DLL files as instructed and no go.

**Comment by RastislavKish** [comment] 2022-10-30 23:30
@ethindp thanks for filling out the issue!
This is an interesting problem. After a bit of playing, I'd say the problem is on RTR's side.
The nvdaControllerClient library is present in the game's directory, but doesn't seem to be actually used.
In fact, to be more specific, it can't even be used, since it's 32-bit, while the game's executable is 64-bit (you can see that using the file command).
Putting a 64-bit library didn't solve the issue, but the architecture conflict raises the question, how compatible is the binary with the dll and whether it's used at all.
Perhaps @Ghorthalon could tell us more?
I tried out the old version of RTR from AGArchive, the one that contained the offline mode. Thisone has a 32-bit executable and the library seemed to work, a connection was established successfully.
The game has actually crashed right in the start, but this is likely Wine related, as I didn't install any additional dependencies.

**Comment by Ghorthalon** [comment] 2022-10-30 23:35
Indeed, RTR does not use NVDA Controller. If I remember right, it changes the window title. I am not sure why I did it this way anymore. This is not a problem with this library.

**Comment by ethindp** [comment] 2022-11-08 20:32
So I've tried this with a few other games and it still doesn't work. No idea what's going wrong but its kinda frustrating.

**Comment by RastislavKish** [comment] 2022-11-08 22:50
@Ghorthalon thank you for your quick response!
@ethindp I'm closing this, since the RTR issue is resolved (at least in terms of nvda2speechd).
If you find a game that you think should work with this project and it doesn't, feel free to open an issue for it!

**Closed as completed by RastislavKish** 2022-11-08 22:50 UTC
